const DATA = [
  {
    firstName: "Mark Angelou",
    lastName: "Jamandre",
    age: 26,
    status: "Married",
  },
  {
    firstName: "Elieser",
    lastName: "Tajanlangit",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Mark Angelou",
    lastName: "Jamandre",
    age: 26,
    status: "Married",
  },
  {
    firstName: "Elieser",
    lastName: "Tajanlangit",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Mark Angelou",
    lastName: "Jamandre",
    age: 26,
    status: "Married",
  },
  {
    firstName: "Elieser",
    lastName: "Tajanlangit",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Mark Angelou",
    lastName: "Jamandre",
    age: 26,
    status: "Married",
  },
  {
    firstName: "Elieser",
    lastName: "Tajanlangit",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
  {
    firstName: "Genesis123",
    lastName: "Tagsip",
    age: 27,
    status: "Single",
  },
];

export default DATA;
